//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRadioApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity;
    using System.Web.Mvc;

    public partial class radiostations
    {
        public int id { get; set; }

        [DisplayName("Station Name")]
        [Required(ErrorMessage = "Please enter the Radio station name")]
        public string name { get; set; }

        [DisplayName("Station URL")]
        [Required(ErrorMessage = "Please enter the Radio station URL")]
        public string url { get; set; }

        [DisplayName("Category")]
        public Nullable<int> categoryId { get; set; }

        [DisplayName("Country")]
        public Nullable<int> countryId { get; set; }

        [DisplayName("Modifier")]
        public string modifiedby { get; set; }

        [DisplayName("Modify Date")]
        public Nullable<System.DateTime> modified_date { get; set; }

        [DisplayName("Category")]
        public virtual category category { get; set; }

        [DisplayName("Country")]
        public virtual country country { get; set; }
    }
}
